CREATE TABLE Users(
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(30) NOT NULL UNIQUE,
password BIGINT UNSIGNED NOT NULL,
email VARCHAR(50)
);
CREATE TABLE Messages(
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
user_id INT(6) UNSIGNED,
message VARCHAR(256),
FOREIGN KEY (user_id) REFERENCES Users(id)
);